backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'posts'
    label: 'Post'
    format: 'json'
    folder: '/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image', required: false, hint: 'OPTIONAL' }
      - { label: 'Body', name: 'body', widget: 'markdown' }